// Generated by CoffeeScript 1.10.0
(function() {
  var DescriptionParser, DescriptionParserResult, S, spu;

  S = require('string');

  spu = require('./stringparserutils').spu;

  DescriptionParser = (function() {
    function DescriptionParser() {}

    DescriptionParser.parseDescription = function(s) {
      var first, ref, ref1, ret, second;
      ret = new DescriptionParserResult();
      if (!S(s).isEmpty()) {
        if (S(s).contains("(+")) {
          ref = spu.splitOnFirst(s, "(+"), first = ref[0], second = ref[1];
          ret.beforeDescription = first;
          ret.description = spu.splitOnLast(second, ")")[0];
          ret.usedAppendDelimiter = true;
        } else if (S(s).contains("(")) {
          ref1 = spu.splitOnFirst(s, "("), first = ref1[0], second = ref1[1];
          ret.beforeDescription = first;
          ret.description = spu.splitOnLast(second, ")")[0];
        } else {
          ret.beforeDescription = s;
        }
      }
      return ret;
    };

    return DescriptionParser;

  })();

  DescriptionParserResult = (function() {
    function DescriptionParserResult() {}

    DescriptionParserResult.prototype.beforeDescription = '';

    DescriptionParserResult.prototype.description = '';

    DescriptionParserResult.prototype.usedAppendDelimiter = false;

    return DescriptionParserResult;

  })();

  module.exports.DescriptionParser = DescriptionParser;

  module.exports.DescriptionParserResult = DescriptionParserResult;

}).call(this);
