// Generated by CoffeeScript 1.10.0
(function() {
  var ShortCut;

  ShortCut = (function() {
    ShortCut.validFrom = 0;

    function ShortCut(key, expansion, wholeDayExpansion) {
      this.key = key;
      this.expansion = expansion;
      this.wholeDayExpansion = wholeDayExpansion != null ? wholeDayExpansion : false;
    }

    return ShortCut;

  })();

  module.exports = ShortCut;

}).call(this);
