// Generated by CoffeeScript 1.10.0
(function() {
  var TimeItem, WorkItem;

  TimeItem = require('./timeitem');

  WorkItem = (function() {
    function WorkItem(start, end, project, position, description, shortCut, originalString) {
      this.start = start;
      this.end = end;
      this.project = project;
      this.position = position;
      this.description = description;
      this.shortCut = shortCut;
      this.originalString = originalString;
    }

    WorkItem.prototype.projectPosition = function() {};

    WorkItem.prototype.hoursDuration = function() {
      return TimeItem.difference(this.start, this.end);
    };

    return WorkItem;

  })();

  module.exports = WorkItem;

}).call(this);
